Bridge.assembly("TS_AngularJS.BridgeConversion", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","TS_AngularJS.BridgeConversion"];
    $m("TS_AngularJS.BridgeConversion.App", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"InitLocationProvider","is":true,"t":8,"pi":[{"n":"locationProvider","pt":Bridge.virtualc("angular.ILocationProvider"),"ps":0}],"sn":"InitLocationProvider","rt":$n[0].Void,"p":[Bridge.virtualc("angular.ILocationProvider")]},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void},{"a":1,"n":"TodoCtrlInitializerDelegate","is":true,"t":4,"rt":Bridge.virtualc("angular.IControllerConstructor.IControllerConstructorCtorFn"),"sn":"TodoCtrlInitializerDelegate"}]}; }, $n);
    $m("TS_AngularJS.BridgeConversion.TodoCtrl", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[Bridge.virtualc("angular.IHttpService"),Bridge.virtualc("angular.ITimeoutService"),$n[1].ITodoCtrlScope],"pi":[{"n":"httpService","pt":Bridge.virtualc("angular.IHttpService"),"ps":0},{"n":"timeoutService","pt":Bridge.virtualc("angular.ITimeoutService"),"ps":1},{"n":"scope","pt":$n[1].ITodoCtrlScope,"ps":2}],"sn":"ctor"},{"a":1,"n":"_httpService","t":4,"rt":Bridge.virtualc("angular.IHttpService"),"sn":"_httpService","ro":true},{"a":1,"n":"_scope","t":4,"rt":$n[1].ITodoCtrlScope,"sn":"_scope","ro":true},{"a":1,"n":"_timeOutService","t":4,"rt":Bridge.virtualc("angular.ITimeoutService"),"sn":"_timeOutService","ro":true}]}; }, $n);
    $m("TS_AngularJS.BridgeConversion.IHasScopeSpy", function () { return {"att":161,"a":2,"m":[{"ab":true,"a":2,"n":"Spy","t":16,"rt":$n[0].Object,"g":{"ab":true,"a":2,"n":"get_Spy","t":8,"rt":$n[0].Object,"fg":"TS_AngularJS$BridgeConversion$IHasScopeSpy$Spy"},"s":{"ab":true,"a":2,"n":"set_Spy","t":8,"p":[$n[0].Object],"rt":$n[0].Void,"fs":"TS_AngularJS$BridgeConversion$IHasScopeSpy$Spy"},"fn":"TS_AngularJS$BridgeConversion$IHasScopeSpy$Spy"}]}; }, $n);
    $m("TS_AngularJS.BridgeConversion.ITodoCtrlScope", function () { return {"att":1048705,"a":2,"m":[{"a":3,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Height","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_Height","t":8,"rt":$n[0].Int32,"fg":"Height","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_Height","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"Height"},"fn":"Height"},{"a":2,"n":"Width","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_Width","t":8,"rt":$n[0].Int32,"fg":"Width","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_Width","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"Width"},"fn":"Width"}]}; }, $n);
});
